version: 2

sphinx:
  configuration: docs/conf.py

formats: all

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .
