version: 2

sphinx:
  configuration: docs/conf.py

formats: all

build:
  image: latest

python:
  version: 3.7
  install:
    - method: pip
      extra_requirements:
        - docs
    - method: setuptools
      path: package
